ATTACH DATABASE 'bible_jw.db' AS 'bible'; 
INSERT INTO testament VALUES(NULL, 'old');
INSERT INTO testament VALUES(NULL, 'new');
INSERT INTO testament VALUES(NULL, 'unsanitary');
INSERT INTO book ('id', 'name', 'test_id')
    VALUES  (NULL, "Genesis", "old"),
            (NULL, "Exodus", "old"),
            (NULL, "Leviticus", "old"),
            (NULL, "Numbers", "old"),
            (NULL, "Deuteronomy", "old"),
            (NULL, "Joshua", "old"),
            (NULL, "Judges", "old"),
            (NULL, "Ruth", "old"),
            (NULL, "1 Samuel", "old"),
            (NULL, "2 Samuel", "old"),
            (NULL, "1 Kings", "old"),
            (NULL, "2 Kings", "old"),
            (NULL, "1 Chronicles", "old"),
            (NULL, "2 Chronicles", "old"),
            (NULL, "Ezra", "old"),
            (NULL, "Esther", "old"),
            (NULL, "Job", "old"),
            (NULL, "Psalms", "old"),
            (NULL, "Proverbs", "old"),
            (NULL, "Ecclesiastes", "old"),
            (NULL, "Song of Solomon", "old"),
            (NULL, "Isaiah", "old"),
            (NULL, "Jeremiah", "old"),
            (NULL, "Ezekiel", "old"),
            (NULL, "Daniel", "old"),
            (NULL, "Hosea", "old"),
            (NULL, "Joel", "old"),
            (NULL, "Amos", "old"),
            (NULL, "Obadiah", "old"),
            (NULL, "Jonah", "old"),
            (NULL, "Micah", "old"),
            (NULL, "Nahum", "old"),
            (NULL, "Habakkuk", "old"),
            (NULL, "Zephaniah", "old"),
            (NULL, "Haggai", "old"),
            (NULL, "Zechariah", "old"),
            (NULL, "Malachi", "old"),
            (NULL, "Matthew", "new"),
            (NULL, "Mark", "new"),
            (NULL, "Luke", "new"),
            (NULL, "John", "new"),
            (NULL, "Acts", "new"),
            (NULL, "Romans", "new"),
            (NULL, "1 Corinthians", "new"),
            (NULL, "2 Corinthians", "new"),
            (NULL, "Galatians", "new"),
            (NULL, "Ephesians", "new"),
            (NULL, "Philippians", "new"),
            (NULL, "Colossians", "new"),
            (NULL, "1 Thessalonians", "new"),
            (NULL, "2 Thessalonians", "new"),
            (NULL, "1 Timothy", "new"),
            (NULL, "2 Timothy", "new"),
            (NULL, "Titus", "new"),
            (NULL, "Philemon", "new"),
            (NULL, "Hebrews", "new"),
            (NULL, "James", "new"),
            (NULL, "1 Peter", "new"),
            (NULL, "2 Peter", "new"),
            (NULL, "1 John", "new"),
            (NULL, "2 John", "new"),
            (NULL, "3 John", "new"),
            (NULL, "Jude", "new"),
            (NULL, "Revelation", "new");